src/main/java/com/eletraenergy/configSW/view/LoginBean.java
package com.eletraenergy.configSW.view;

import java.io.Serializable;

import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.stereotype.Component;

import com.eletraenergy.configSW.service.AuthenticationService;

@SuppressWarnings("serial")
@Component("LoginBean")
@Scope("request")
public class LoginBean extends ManagerBean implements Serializable {

	@Autowired
	private AuthenticationService authenticationService;
	
	private String login;
	private String password;
	private String msg;
	
	public void initialLoad() {
	}
	
	public String authenticate() {
		String retorno = "home?faces-redirect=true";
	    
	    String loginMessage = authenticationService.login(login, password);
	    if (!loginMessage.equalsIgnoreCase("ok")) {
	    	this.login = new String();
	    	this.password = new String();
	    	setMsg(loginMessage);
	    	errorMsg(loginMessage, null);
	    	return "invalidLogin";
	    }
	    
		HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
		request.getSession().setAttribute("login", true);
		request.getSession().setAttribute("user", login);
		request.getSession().setAttribute("lastAccess", authenticationService.getLastAccess());
		
		return retorno;
	}
	
	public boolean anyGranted(String value) {
		String[] listGrants = value.split(",");
		if (authenticationService.getUserLogon()!= null) {
			for (GrantedAuthority permissao : authenticationService.getUserLogon().getAuthorities()) {
				for (String grant : listGrants) {
					if (permissao.getAuthority().equals(grant))
						return true;				
				}
			}
		}
		return false;
	}
	
	public String logout() {
		authenticationService.logout();
		return "/login?faces-redirect=true";
	}

	public String getUserName() {
		return authenticationService.getUserLogon().getName();
	}

	public String getLogin() {
		return login;
	}
	
	public void setLogin(String login) {
		this.login = login;
	}
	
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getMsg() {
		return msg;
	}
	
	public void setMsg(String msg) {
		this.msg = msg;
		getFlashScope().put("msg", msg);
	}
}

src/main/webapp/WEB-INF/templates/footer.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    
    <p:panelGrid columns="3" layout="grid" style="margin-bottom:10px;margin-top:10px;">
      <h:outputText value="Eletra Energy Solution" style="float:left" />
      
      <h:outputLink value="#">
			<h:outputText value="#{bundle.version}: 0.0.2 (build 0002) #{bundle.updateon}: 29/12/2017 18:50" />
	  </h:outputLink>
      
      <h:outputText value="#{bundle.lastAccess}: #{sessionScope.lastAccess}" style="float:right"/>
	</p:panelGrid>
    
</ui:composition>

src/main/webapp/WEB-INF/templates/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"	
	xmlns:sec="http://www.springframework.org/security/facelets/tags"  >
	<f:view contentType="text/html" locale="#{localeBean.appLocale}"> 
	    <h:head>
	        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	        <title>#{bundle.title}</title>
 		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/themify-icons.min.css"/> 
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/weather-icons.min.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/jquery-ui.min.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/jquery-ui.structure.min.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/jquery-ui.theme.min.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/plot.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/bootstrap.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/ui.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/main.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/toastr.min.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/select2.css"/>
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/font-awesome.min.css"/>    
		    <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/_style.css"/>
            <link rel="stylesheet" type="text/css" href="#{facesContext.externalContext.request.contextPath}/css/accordion.css" class="ng-scope"/>

			<link href="#{facesContext.externalContext.request.contextPath}/img/favicon.ico" rel="shortcut icon" type="image/x-icon" /> 
		</h:head>
	    <h:body>
  			<ui:insert name="content">
			<!-- Conteúdo da pagina!!! -->
			</ui:insert>	                
			<p:ajaxStatus>
	     			<f:facet name="start">
	            <div class="loading" id="divLoading">
				    <center>
				        <div class="modalloading" style="padding-top: 110px;">
				            <div class="progressbar-sm progress-striped active progress ng-isolate-scope" >
				                <div class="progress-bar progress-bar-info" style="width: 100%;"></div>
				            </div>
				       </div>
				
				    </center>
				</div>
	     			</f:facet>
	     			<f:facet name="complete">
	         			<h:outputText value="" />
	     			</f:facet>
			</p:ajaxStatus>
	   </h:body>
	</f:view>
</html>

src/main/webapp/WEB-INF/templates/menu.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pa="http://primefaces.org/barcelona">
    
    <div class="layout-sidebar #{guestPreferences2.darkMenu ? 'layout-sidebar-dark': ''}">
        <pa:tabMenu>
            <pa:tab icon="home" title="#{bundle.title}">
                <h:form id="menu-form">
                    <pa:menu widgetVar="me">

                        <p:submenu icon="description" id="register" label="#{bundle.register}" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_TYPE,ROLE_REG_MEASURING_INSTRUMENT_MANUFACTURER,ROLE_REG_MEASURING_INSTRUMENT_MODEL,ROLE_REG_MEASURING_INSTRUMENT_PLACE_USE,ROLE_REG_MEASURING_INSTRUMENT_STANDARD,ROLE_REG_MEASURING_Instrument,ROLE_REG_CALIBRATION_LABORATORY,ROLE_REG_NOTIFICATION_USER,ROLE_REG_NOTIFICATION_RULES')}">
	                        
                            <p:submenu icon="devices" id="devices" label="#{bundle.measuringInstrument}" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_TYPE,ROLE_REG_MEASURING_INSTRUMENT_MANUFACTURER,ROLE_REG_MEASURING_INSTRUMENT_MODEL,ROLE_REG_MEASURING_INSTRUMENT_PLACE_USE,ROLE_REG_MEASURING_INSTRUMENT_STANDARD,ROLE_REG_MEASURING_Instrument')}">
                            
                            	<p:submenu icon="dehaze" id="auxTables" label="#{bundle.auxTable}" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_TYPE,ROLE_REG_MEASURING_INSTRUMENT_MANUFACTURER,ROLE_REG_MEASURING_INSTRUMENT_MODEL,ROLE_REG_MEASURING_INSTRUMENT_PLACE_USE,ROLE_REG_MEASURING_INSTRUMENT_STANDARD')}">
                            	
					            	<p:menuitem icon="add" id="measuringInstrumentType" value="#{bundle.measuringInstrumentType}" url="/pages/cruds/createMeasuringInstrumentType.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_TYPE')}" />
					            	<p:menuitem icon="add" id="measuringInstrumentManufacturer" value="#{bundle.measuringInstrumentManufacturer}" url="/pages/cruds/createMeasuringInstrumentManufacturer.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_MANUFACTURER')}"/>
					            	<p:menuitem icon="add" id="measuringInstrumentModel" value="#{bundle.measuringInstrumentModel}" url="/pages/cruds/createMeasuringInstrumentModel.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_MODEL')}" />
					            	<p:menuitem icon="add" id="measuringInstrumentPlaceUse" value="#{bundle.measuringInstrumentPlaceUse}" url="/pages/cruds/createMeasuringInstrumentPlaceUse.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_PLACE_USE')}"/>
                                    <p:menuitem icon="add" id="measuringInstrumentDepartment" value="#{bundle.measuringInstrumentDepartment}" url="/pages/cruds/createMeasuringInstrumentDepartment.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_DEPARTMENT')}"/>
                                    <p:menuitem icon="add" id="measuringInstrumentStandard" value="#{bundle.measuringInstrumentStandard}" url="/pages/cruds/createMeasuringInstrumentStandard.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT_STANDARD')}"/>
					            						            	
				            	</p:submenu>
				            	
				            	<p:menuitem icon="create" id="measuringInstrument" value="#{bundle.measuringInstrument}" url="/pages/cruds/searchMeasuringInstrument.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_MEASURING_INSTRUMENT')}"/>
				            	
			            	</p:submenu>
							

                            <p:submenu icon="memory" id="laboratories" label="#{bundle.calibrationLaboratory}" rendered="#{LoginBean.anyGranted('ROLE_REG_CALIBRATION_LABORATORY')}">
                                <p:menuitem icon="create" id="calibrationLaboratory" value="#{bundle.calibrationLaboratory}" url="/pages/cruds/searchCalibrationLaboratory.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_CALIBRATION_LABORATORY')}"/>

                            </p:submenu>

                            <!--
							<p:submenu icon="subtitles" id="notification" label="#{bundle.notification}" rendered="#{LoginBean.anyGranted('ROLE_REG_NOTIFICATION_USER,ROLE_REG_NOTIFICATION_RULES')}">
				            	<p:menuitem disabled="true" icon="create" id="notificationUser" value="#{bundle.notificationUser}" url="/pages/cruds/searchNotificationUser.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_NOTIFICATION_USER')}"/>
				            	<p:menuitem disabled="true" icon="create" id="notificationRules" value="#{bundle.notificationRules}" url="/pages/cruds/searchNotificationRules.faces" rendered="#{LoginBean.anyGranted('ROLE_REG_NOTIFICATION_RULES')}"/>
			            	</p:submenu>
                            -->
			            	 
						</p:submenu>
							
						<!-- 
						<p:submenu icon="widgets" id="operation" label="#{bundle.operation}" rendered="#{LoginBean.anyGranted('ROLE_MOV_ME')}">
			            	<p:menuitem disabled="true" icon="create" id="operationMeasuringInstrument" value="#{bundle.measuringInstrument}" url="/pages/cruds/searchOperationMeasuringEquipament.faces" rendered="#{LoginBean.anyGranted('ROLE_MOV_ME')}"/>
		            	</p:submenu>

                        <p:submenu id="search" label="#{bundle.search}" icon="search" expanded="true" rendered="#{LoginBean.anyGranted('ROLE_RPT_ME')}">
	                        <p:menuitem disabled="true" icon="subtitles" value="#{bundle.measuringInstrument}" url="/pages/reportMeasuringEquipament.faces" rendered="#{LoginBean.anyGranted('ROLE_RPT_ME')}"/>
                        </p:submenu>
                        -->
                         
                        <p:submenu id="adminitration" label="#{bundle.administration}" icon="portrait" expanded="true" rendered="#{LoginBean.anyGranted('ROLE_ADM')}">
                            <p:menuitem icon="people" value="#{bundle.users}" url="/pages/administration/searchUsers.faces" rendered="#{LoginBean.anyGranted('ROLE_ADM')}"/>
                        </p:submenu>
 
                    </pa:menu>
                </h:form>
            </pa:tab>
        </pa:tabMenu>        
    </div>
</ui:composition>

src/main/webapp/WEB-INF/templates/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title><ui:insert name="title">Eletra-Metrologia</ui:insert></title>
        <h:outputScript name="js/nanoscroller.js" library="barcelona-layout" />
        <h:outputScript name="js/layout.js" library="barcelona-layout" />
        <h:outputScript name="js/ripple.js" library="barcelona-layout" />
        <ui:insert name="head"/>
		<link rel="stylesheet" type="text/css" media="all" href="#{facesContext.externalContext.request.contextPath}/css/configSWNew.css"  />
    </h:head>

    <h:body styleClass="main-body">
		<f:view contentType="text/html" locale="#{localeBean.appLocale}">
	        <div class="layout-wrapper #{guestPreferences2.overlayMenu ? 'layout-overlay-menu' : null} #{guestPreferences2.orientationRTL ? 'layout-rtl' : null}">
	            <ui:include src="./topbar.xhtml" />
	            <ui:include src="./menu.xhtml" />
	            
	            <div class="layout-main">
	                <div class="layout-main-content">
	                    <ui:insert name="content"/>
	                    
	                    <ui:include src="./footer.xhtml" />
	                </div>
	            </div>
	        </div>
	        
	        <p:ajaxStatus style="width:32px;height:32px;position:fixed;right:7px;bottom:7px">
	           <f:facet name="start">
	               <i class="fa fa-circle-o-notch fa-spin ajax-loader" aria-hidden="true"></i>
	           </f:facet>
	
	           <f:facet name="complete">
	               <h:outputText value="" />
	           </f:facet>
	       </p:ajaxStatus>
      	</f:view>  
        <h:outputStylesheet name="css/nanoscroller.css" library="barcelona-layout" />
        <h:outputStylesheet name="css/animate.css" library="barcelona-layout" />
        <h:outputStylesheet name="css/ripple.css" library="barcelona-layout" />
        <h:outputStylesheet name="css/layout-#{guestPreferences2.layout}.css" library="barcelona-layout" />
    </h:body>

</html>

src/main/webapp/WEB-INF/templates/topbar.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pa="http://primefaces.org/barcelona">
    <div class="topbar">
        <div class="logo" >
        	<img src="#{facesContext.externalContext.request.contextPath}/img/logo_login.png" />
	    </div>
        <h:link outcome="/home">
		    <svg 
				 xmlns="http://www.w3.org/2000/svg"
				 xmlns:xlink="http://www.w3.org/1999/xlink"
				 width="417px" height="60px" style="margin-left: 1px;opacity: 1.00;">
				<text font-family="Roboto" fill="rgb(192,192,192)" font-size="25px" x="0px" y="40px">Metrologia</text>
			</svg>
        </h:link>
        
        <a id="topbar-menu-button" href="#">
            <i class="fa fa-bars"></i>
        </a>
        
        <ul class="topbar-menu fadeInDown animated">
            <li class="profile-item" style="margin-top: 0px;">
                <a href="#">                            
                    <div class="profile-image">
                        <i class="topbar-icon fa fa-fw fa-user"></i>
                    </div>
                    <div class="profile-info">
                        <span class="topbar-item-name profile-name">#{LoginBean.userName}</span>
                    </div>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="topbar-icon fa fa-fw fa-cog"></i>
                    <span class="topbar-item-name">#{bundle.settings}</span>
                </a>
                <ul class="animated">
		        <h:form id="menu-topbar">
		        
                    <li role="menuitem">
                        <a href="#">
                            <i class="fa fa-fw fa-paint-brush"></i>
                            <span>#{bundle.menuModes}</span>
                        </a>
                        <ul class="animated">
        		            <li role="menuitem">
        		            	<p:commandLink id="menu1" value="Light Menu" icon="&#xE893;" actionListener="#{guestPreferences2.setDarkMenu(false)}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="menu2" value="Dark Menu" icon="&#xE892;" actionListener="#{guestPreferences2.setDarkMenu(true)}" ajax="false"/>
        		            </li>
						</ul>        		            
                    </li>
                    <li role="menuitem">
                        <a href="#">
                            <i class="fa fa-fw fa-star-o"></i>
                            <span>#{bundle.orientation}</span>
                        </a>
                        <ul class="animated">
        		            <li role="menuitem">
        		            	<p:commandLink id="om_ltr" value="LTR" icon="&#xE236;" actionListener="#{guestPreferences2.setOrientationRTL(false)}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="om_rtl" value="RTL" icon="&#xE237;" actionListener="#{guestPreferences2.setOrientationRTL(true)}" ajax="false"/>
        		            </li>
						</ul>        		            
                    </li>
                    <li role="menuitem">
                        <a href="#">
                            <i class="fa fa-fw fa-lock"></i>
                            <span>#{bundle.themes}</span>
                        </a>
                        <ul class="animated">
        		            <li role="menuitem">
        		            	<p:commandLink id="theme1" value="Blue - Amber" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('blue')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme2" value="Teal - Amber" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('teal')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme3" value="Blue Grey - Green" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('blue-grey')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme4" value="Cyan - Yellow" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('cyan')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme5" value="Dark - Blue" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('dark-blue')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme6" value="Dark - Green" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('dark-green')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme7" value="Light Blue - Green" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('light-blue')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme8" value="Indigo - Cyan" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('indigo')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme9" value="Deep Purple - Pink" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('deep-purple')}" ajax="false"/>
        		            </li>
        		            <li role="menuitem">
        		            	<p:commandLink id="theme10" value="Green - Yellow" icon="&#xE40A;" actionListener="#{guestPreferences2.setTheme('green')}" ajax="false"/>
        		            </li>
						</ul>
                    </li>
                    <li role="menuitem">
			    		<p:commandLink id="logout_menu_option" value="#{bundle.exit}" action="#{LoginBean.logout}" title="#{bundle.exit}" ajax="false"/>
           			</li>
				</h:form>                
                </ul>
            </li>
	        <h:form id="menu-language">
	            <!-- flag-en -->
	            <!-- flag-pt -->
	            <li role="menuitem">
					<p:commandLink id="en" update="@all" actionListener="#{localeBean.change2English}" styleClass="ui-icon-flag-en" immediate="true" ajax="false" rendered="#{localeBean.appLocale.language != 'en'}" />  
	            </li>
	            <li role="menuitem">
					<p:commandLink id="pt" update="@all" action="#{localeBean.change2Brasil}" styleClass="ui-icon-flag-pt" immediate="true" ajax="false" rendered="#{localeBean.appLocale.language != 'pt'}"/>
	            </li>
			</h:form>                
        </ul>        
    </div>
</ui:composition>