src/main/java/com/eletraenergy/configSW/model/ConfigCommand.java
package com.eletraenergy.configSW.model;

import java.util.ArrayList;

public class ConfigCommand {
	
	private String hashCode;
	private String meterFamilyName;
	private String meterModelName;
	private String tdsNumber;
	private Firmware firmware;
	private ArrayList<ManufactStep2> listOfManufactStep = new ArrayList<ManufactStep2>();

	public String getHashCode() {
		return hashCode;
	}
	public void setHashCode(String hashCode) {
		this.hashCode = hashCode;
	}
	public String getMeterFamilyName() {
		return meterFamilyName;
	}
	public void setMeterFamilyName(String meterFamilyName) {
		this.meterFamilyName = meterFamilyName;
	}
	public String getMeterModelName() {
		return meterModelName;
	}
	public void setMeterModelName(String meterModelName) {
		this.meterModelName = meterModelName;
	}
	public String getTdsNumber() {
		return tdsNumber;
	}
	public void setTdsNumber(String tdsNumber) {
		this.tdsNumber = tdsNumber;
	}
	public Firmware getFirmware() {
		return firmware;
	}
	public void setFirmware(Firmware firmware) {
		this.firmware = firmware;
	}
	public ArrayList<ManufactStep2> getListOfManufactStep() {
		return listOfManufactStep;
	}
	public void setListOfManufactStep(ArrayList<ManufactStep2> listOfManufactStep) {
		this.listOfManufactStep = listOfManufactStep;
	}
}

src/main/java/com/eletraenergy/configSW/model/ConfigTechSpec.java
package com.eletraenergy.configSW.model;

import java.util.ArrayList;

public class ConfigTechSpec {
	private String MeterFamilyName;
	private String MeterModelName;
	private String TDS_Number;
	private String state_identifier;
	private String state_timestamp;
	private String change_version;
	private String change_timestamp;
	private String change_state_identifier;
	private ArrayList<ItemSpecCategory> ListOfItemSpecCategory = new ArrayList<ItemSpecCategory>();
	
	public String getNM_MeterFamily() {
		return MeterFamilyName;
	}
	public void setNM_MeterFamily(String nM_MeterFamily) {
		MeterFamilyName = nM_MeterFamily;
	}
	public String getNM_MeterModel() {
		return MeterModelName;
	}
	public void setNM_MeterModel(String nM_MeterModel) {
		MeterModelName = nM_MeterModel;
	}
	public String getTDS_Number() {
		return TDS_Number;
	}
	public void setTDS_Number(String tDS_Number) {
		TDS_Number = tDS_Number;
	}
	public ArrayList<ItemSpecCategory> getListOfItemSpecCategory() {
		return ListOfItemSpecCategory;
	}
	public void setListOfItemSpecCategory(ArrayList<ItemSpecCategory> listOfItemSpecCategory) {
		ListOfItemSpecCategory = listOfItemSpecCategory;
	}
	public String getState_identifier() {
		return state_identifier;
	}
	public void setState_identifier(String state_identifier) {
		this.state_identifier = state_identifier;
	}
	public String getState_timestamp() {
		return state_timestamp;
	}
	public void setState_timestamp(String state_timestamp) {
		this.state_timestamp = state_timestamp;
	}
	public String getChange_version() {
		return change_version;
	}
	public void setChange_version(String change_version) {
		this.change_version = change_version;
	}
	public String getChange_timestamp() {
		return change_timestamp;
	}
	public void setChange_timestamp(String change_timestamp) {
		this.change_timestamp = change_timestamp;
	}
	public String getChange_state_identifier() {
		return change_state_identifier;
	}
	public void setChange_state_identifier(String change_state_identifier) {
		this.change_state_identifier = change_state_identifier;
	}
	@Override
	public String toString() {
		return "ConfigTechSpec [MeterFamilyName=" + MeterFamilyName
				+ ", MeterModelName=" + MeterModelName + ", TDS_Number="
				+ TDS_Number + ", state_identifier=" + state_identifier
				+ ", state_timestamp=" + state_timestamp + ", change_version="
				+ change_version + ", change_timestamp=" + change_timestamp
				+ ", change_state_identifier=" + change_state_identifier
				+ ", ListOfItemSpecCategory=" + ListOfItemSpecCategory + "]";
	}
	
	
}

src/main/java/com/eletraenergy/configSW/view/ConfigCommandBean.java
package com.eletraenergy.configSW.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.eletraenergy.configSW.model.ConfigCommand;
import com.eletraenergy.configSW.model.ConfigModel;
import com.eletraenergy.configSW.model.ConfigTechSpec;
import com.eletraenergy.configSW.model.ItemOptionSpec;
import com.eletraenergy.configSW.model.ItemSpec;
import com.eletraenergy.configSW.model.ItemSpecCategory;
import com.eletraenergy.configSW.model.ManufactStep2;
import com.eletraenergy.configSW.model.MeterCommand;
import com.eletraenergy.configSW.model.OptionType;
import com.eletraenergy.configSW.util.ResourceBundle;


/**
* Use case : Config Command
* 
* @since   : Fev 10, 2017, 19:01:20
* @author  : raphael.ferreira
*/

@Component("configCommandBean")
@Scope("session")
public class ConfigCommandBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = -2632711068730591195L;
	private List<MeterCommand> meterCommands;
	private ConfigTechSpec configTechSpec;
	private List<ConfigModel> configModel;


	public void loadInit() {
		ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
		Map<String, Object> sessionMap = externalContext.getSessionMap();
		ConfigCommand configCommand = (ConfigCommand) sessionMap.get("configCommand"); 
		configTechSpec = (ConfigTechSpec) sessionMap.get("configTechSpec"); 
		prepareConfigModel();
		meterCommands = new ArrayList<MeterCommand>();
		for (ManufactStep2 manufactStep : configCommand.getListOfManufactStep()) {
			String manufactStepName = manufactStep.getManufactStepName();
			if (manufactStep.getListOfMeterCommand()==null || manufactStep.getListOfMeterCommand().isEmpty()){
				MeterCommand meterCommand = new MeterCommand();
				meterCommand.setCmdTitle(ResourceBundle.getMessage("withoutCommands"));
				meterCommand.setStage(manufactStepName);
				meterCommands.add(meterCommand);
			}else{
				for (MeterCommand meterCommand : manufactStep.getListOfMeterCommand()) {
					meterCommand.setStage(manufactStepName);
					meterCommands.add(meterCommand);
				}
			}
		}
	}
	
	private void prepareConfigModel() {
		configModel = new ArrayList<ConfigModel>();
		for (ItemSpecCategory item : configTechSpec.getListOfItemSpecCategory()) {
			String nm_TypeItemSpec = null;
		    for (ItemSpec itemSpec : item.getListOfItemSpec()) {
		    	OptionType optionType = OptionType.Read;;
		    	List<String> options = new ArrayList<String>();
		    	String validation = null;
		    	String type = null;
		    	String valMaxDigInt = null;
		    	String valMaxDigDec = null;
		    	String valMaxDig = null;
		    	String maxSel = null;
		    	String valMin = null;
		    	String valMax = null;
		    	boolean isRequired = false;
		    	String value = "";
		    	if (itemSpec.getItemSpecValue()==null || itemSpec.getItemSpecValue().isEmpty()){
		    		if(itemSpec.getListOfItemOptionSpec() != null && !itemSpec.getListOfItemOptionSpec().isEmpty()){
				    	for (ItemOptionSpec i : itemSpec.getListOfItemOptionSpec()) {
							value = value + i.getNM_ItemOptionSpec() + ", ";
						}
				    	value = value.substring(0, value.length()-2);
		    		}
		    	}else{
			    	value = itemSpec.getItemSpecValue();
		    	}
		    		
    			
		    	String category = "";
		    	if (nm_TypeItemSpec == null || !nm_TypeItemSpec.equals(item.getNM_TypeItemSpec())) {
			    	nm_TypeItemSpec = item.getNM_TypeItemSpec();
			    	category = nm_TypeItemSpec;
				}else{
					category = "";
				}
				configModel.add(new ConfigModel(category, itemSpec.getNM_ItemSpec(), options, value, optionType, validation, type, valMaxDigInt, valMaxDigDec, valMaxDig, maxSel, valMin, valMax, isRequired));
			}
			
		}
	}	
	public String back(){
		return "configTechSpec";
	}

	public String export(){
		return "configTechSpec";
	}

	public String exportCommands(){
		return null;
	}
	
	public List<MeterCommand> getMeterCommands() {
		return meterCommands;
	}

	public void setMeterCommands(List<MeterCommand> meterCommands) {
		this.meterCommands = meterCommands;
	}

	public List<ConfigModel> getConfigModel() {
		return configModel;
	}

	public void setConfigModel(List<ConfigModel> configModel) {
		this.configModel = configModel;
	}
	

}

src/main/java/com/eletraenergy/configSW/view/SimulationBean.java
package com.eletraenergy.configSW.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletResponse;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.eletraenergy.configSW.model.ColumnModel;
import com.eletraenergy.configSW.model.FilterModel;
import com.eletraenergy.configSW.model.MeterLine;
import com.eletraenergy.configSW.model.MeterModel;
import com.eletraenergy.configSW.model.Tds;
import com.eletraenergy.configSW.model.TdsModel;
import com.eletraenergy.configSW.model.TdsSpec;
import com.eletraenergy.configSW.model.TdsSpecOption;
import com.eletraenergy.configSW.model.TdsStateIdentifier;
import com.eletraenergy.configSW.model.ViewTDS;
import com.eletraenergy.configSW.model.ViewTDSSpec;
import com.eletraenergy.configSW.model.ViewTdsAud;
import com.eletraenergy.configSW.service.MeterLineService;
import com.eletraenergy.configSW.service.MeterModelService;
import com.eletraenergy.configSW.service.TdsService;
import com.eletraenergy.configSW.service.TdsSpecService;
import com.eletraenergy.configSW.service.ViewTDSService;
import com.eletraenergy.configSW.service.ViewTDSSpecService;
import com.eletraenergy.configSW.service.ViewTdsAudService;
import com.eletraenergy.configSW.util.ExcelUtils;
import com.eletraenergy.configSW.util.ResourceBundle;

/**
* Use case : Simulation
* 
* @since   : Jan 22, 2017, 23:01:20 AM
* @author  : raphael.ferreira
*/

@Component("simulationBean")
@Scope("view")
public class SimulationBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = -1054159219288063324L;

	@Autowired
	private MeterLineService meterLineService;
	@Autowired
	private MeterModelService meterModelService;
	@Autowired
	private ViewTDSSpecService viewTDSSpecService;
	@Autowired
	private ViewTDSService viewTDSService;
	@Autowired
	private TdsSpecService tdsSpecService;
	@Autowired
	private TdsService tdsService;
	@Autowired
	private ViewTdsAudService viewTdsAudService;

	
	MeterLine meterLine;
	MeterModel meterModel;
	String tds;
	private TdsModel selectedTds;
	List<MeterLine> meterLines;
	List<MeterModel> meterModels;
	private TdsStateIdentifier state;
	private List<FilterModel> filters;
	private List<ViewTDS> tdss;
	private List<TdsModel> tdsList;
	private List<ColumnModel> columns;
	
	public void loadInit() {
		if (meterLines == null){
			meterLines = meterLineService.findAll();
			loadFilters();
			search();
		}
	}
	
	public void loadMeterModels() {
		if(meterLine==null){
			meterModels = meterModelService.findAll();
		}else{
			meterModels = meterModelService.findbyLine(meterLine);
		}
		meterModel = null;
		loadFilters();
	}
	
	public void exportToPDF(TdsModel tdsModel) {
		
		ExcelUtils excelUtils = new ExcelUtils(true);
		
		final FacesContext facesContext = FacesContext.getCurrentInstance();
	    final ExternalContext externalContext = facesContext.getExternalContext();
	    
	    externalContext.responseReset();
	    externalContext.setResponseContentType("application/octet-stream");
	    externalContext.setResponseHeader("Content-Disposition", "attachment;filename=tds-export.xls");

	    try {
	    	
	    	Tds tds = tdsService.checkIdentifier(tdsModel.getTds());
	    	List<TdsSpecOption> listOfTdsSpecOption = tds.getTemplate().getTdsSpecOptions();
	    	List<TdsSpec> listOfTdsSpec = tdsSpecService.findAll();
	    	ViewTdsAud viewTdsAud = viewTdsAudService.findById(tds.getId());
	    	
			HSSFWorkbook exportTdsToExcel = excelUtils.exportTdsToExcel(listOfTdsSpec, listOfTdsSpecOption, tds, viewTdsAud);
			
			exportTdsToExcel.write(
					((HttpServletResponse) externalContext.getResponse()).getOutputStream());
			
			facesContext.responseComplete();
			
		} catch (Exception e) {
			
			externalContext.responseReset();
			errorMsg(ResourceBundle.getMessage("tdsExportToExcelError"), null);
		}
	}

	public void loadFilters() {
		List<ViewTDSSpec> listTDSSpec = null;
		if (meterLine == null && meterModel == null){
			listTDSSpec = viewTDSSpecService.findAll();
		}else{
			if (meterModel == null) {
				listTDSSpec = viewTDSSpecService.findByLine(meterLine);	
			} else {
				listTDSSpec = viewTDSSpecService.findByLineAndModel(meterLine, meterModel);
			}
		}
		
		filters = new ArrayList<FilterModel>();
		Long id = null;
		List<String> listOptions = null;
		String option = null;
		for (ViewTDSSpec viewTDSSpec : listTDSSpec) {
			if (id == null || !id.equals(viewTDSSpec.getId())){
				if (listOptions != null){
					FilterModel filtroModel = new FilterModel(option, null, listOptions, null);
					filters.add(filtroModel);
				}
				id = viewTDSSpec.getId();
				option = viewTDSSpec.getName();
				listOptions = new ArrayList<String>();
			}
			listOptions.add(viewTDSSpec.getOptionName());
		}
		//The last
		if (listOptions != null){
			FilterModel filtroModel = new FilterModel(option, null, listOptions, null);
			filters.add(filtroModel);
		}
	}

	//Limpa filtros de tds
	public void clear() {
		state = null;
		meterModel = null;
		meterLine = null;
		tds = null;
		loadFilters();
	}
	
	public void search() {
		tdsList = new ArrayList<TdsModel>();
		List<FilterModel> validFilters = new ArrayList<FilterModel>();
		if (tds == null || tds.isEmpty() ){
			for (FilterModel filterModel : filters) {
				if(filterModel.getValue() != null && !filterModel.getValue().isEmpty()){
					validFilters.add(filterModel);
				}
			}
		}
		
		tdss = viewTDSService.findConfig(meterLine, meterModel, tds, validFilters, state);
		
		List<String> specNames = new ArrayList<String>();

		//Descubrir todos os specNames
		for (ViewTDS tds : tdss) {
			boolean isFilter = false;
			for (FilterModel validFilter : validFilters) {
				if(validFilter.getHeader().equals(tds.getTdsSpecName())){
					isFilter = true;
				}
			}
			if (!isFilter && !specNames.contains(tds.getTdsSpecName())) {
				specNames.add(tds.getTdsSpecName());
			}
		}
		
		//Montar as colunas
		columns = new ArrayList<ColumnModel>();
		for (String spec : specNames) {
			columns.add(new ColumnModel(spec, spec));
		}
		

		//Criar os TdsModel
		String tdsNumber = null; 
		TdsModel tdsModel = null;
		for (ViewTDS tds : tdss) {
			if(tdsNumber == null || !tdsNumber.equals(tds.getTdsNumber())){
				if(tdsModel != null){
					tdsList.add(tdsModel);
				}
				tdsNumber = tds.getTdsNumber();
				tdsModel = new TdsModel(tds.getState(), tdsNumber, tds.getMeterLineName(), tds.getMeterModelName(), tds.getConfigCode(), new ArrayList<String>());
//				tdsModel.setTds(tdsNumber);
//				tdsModel.setConfigCode(tds.getConfigCode());
				tdsModel.setValues(new ArrayList<String>());
				//Inicializar todos os valores
				for (int i = 0; i < columns.size(); i++) {
					tdsModel.getValues().add(ResourceBundle.getMessage("notDefined"));
				}
			}
			int i = 0;
			for (ColumnModel column : columns) {
				if (column.getHeader().equals(tds.getTdsSpecName())){
					tdsModel.getValues().set(i, tds.getTdsSpecOptionName());
				}
				i = i + 1;
			}
		}
				
		//The Last
		if (tdsModel != null){
			tdsList.add(tdsModel);
		}
	}

	public MeterLine getMeterLine() {
		return meterLine;
	}

	public void setMeterLine(MeterLine meterLine) {
		this.meterLine = meterLine;
	}

	public MeterModel getMeterModel() {
		return meterModel;
	}

	public void setMeterModel(MeterModel meterModel) {
		this.meterModel = meterModel;
	}

	public String getTds() {
		return tds;
	}

	public void setTds(String tds) {
		this.tds = tds;
	}

	public List<MeterLine> getMeterLines() {
		return meterLines;
	}

	public void setMeterLines(List<MeterLine> meterLines) {
		this.meterLines = meterLines;
	}

	public List<MeterModel> getMeterModels() {
		return meterModels;
	}

	public void setMeterModels(List<MeterModel> meterModels) {
		this.meterModels = meterModels;
	}

 	public List<FilterModel> getFilters() {
		return filters;
	}

	public void setFilters(List<FilterModel> filters) {
		this.filters = filters;
	}

	public List<TdsModel> getTdsList() {
		return tdsList;
	}

	public void setTdsList(List<TdsModel> tdsList) {
		this.tdsList = tdsList;
	}

	public List<ColumnModel> getColumns() {
		return columns;
	}

	public void setColumns(List<ColumnModel> columns) {
		this.columns = columns;
	}

	public TdsModel getSelectedTds() {
		return selectedTds;
	}

	public void setSelectedTds(TdsModel selectedTds) {
		this.selectedTds = selectedTds;
	}

	public Boolean getSelect() {
		String viewId = FacesContext.getCurrentInstance().getViewRoot().getViewId();
		
		return viewId.contains("simulation");
	}

	public String getTitle() {
		if (getSelect()){
			return ResourceBundle.getMessage("simulation");
		}else{
			return ResourceBundle.getMessage("tdsAdvanced");
		}
	}

	public TdsStateIdentifier[] getStates() {
		return TdsStateIdentifier.values();
	}

	public TdsStateIdentifier getState() {
		return state;
	}

	public void setState(TdsStateIdentifier state) {
		this.state = state;
	}
}

src/main/webapp/pages/simulation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="../WEB-INF/templates/template.xhtml"
	  xmlns="http://www.w3.org/1999/xhtml"     
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:h="http://java.sun.com/jsf/html"
 	  xmlns:c="http://java.sun.com/jsp/jstl/core"
	  xmlns:p="http://primefaces.org/ui" >
	<ui:define name="content">
		<f:metadata>
		   <f:event type="preRenderView" listener="#{simulationBean.loadInit}" />	
		</f:metadata>
		
		<h:form id="frmSimulation" styleClass="formularios box-border" prependId="false">
			<ui:include src="tdsFilter.xhtml"/>
            <p:commandButton value="#{bundle.next}" action="#{configTechSpecBean.loadTds}" ajax="true" icon="ui-icon-save" styleClass="green-btn flat" style="float: right;" update=":frmSimulation">  
                <f:setPropertyActionListener value="#{simulationBean.selectedTds}" target="#{configTechSpecBean.selectedTds}" />
            </p:commandButton>  				         
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/pages/tdsFilter.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

	<p:growl showDetail="false" autoUpdate="true" sticky="true" style="text-align: left;"/>  

	<p:panel id="basic" header="" footer="" toggleable="false">
              	 
          <f:facet name="header">
		  <h:panelGrid columns="2">
		    <span class="ui-icon ui-icon-apps" />
		    <h:outputText value="#{simulationBean.getTitle()}" style="font-weight:bold;text-transform: uppercase" />
		  </h:panelGrid>
		</f:facet>

           <f:facet name="footer">
			<div class="table-data">
				<p:outputPanel id="table">
					<p:dataTable var="tds" value="#{simulationBean.tdsList}" emptyMessage="#{bundle.noTdsList}"  scrollable="true" scrollWidth="100%" paginatorAlwaysVisible="false"
						paginator="true" rows="10" lazy="false" currentPageReportTemplate="#{bundle.totalRecords}: {totalRecords},  #{bundle.pages}: {currentPage} #{bundle.of} {totalPages}"
						paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"							
						rowIndexVar="rowIx" rowStyleClass="#{rowIx mod 2 eq 0 ? 'even' : 'old'}" selection="#{simulationBean.selectedTds}" rowKey="#{tds.tds}"
                 		rowsPerPageTemplate="10,5,10,15,20" >

						<p:column selectionMode="single" style="width:32px;text-align:center" rendered="#{simulationBean.getSelect()}"/>
						<p:column style="width:32px;text-align:center" rendered="#{!simulationBean.getSelect()}">  
  				            <p:commandButton icon="fa fa-fw fa-file-excel-o" actionListener="#{simulationBean.exportToPDF(tds)}" title="#{bundle.exportTDStoExcel}" ajax="false"/> 
						</p:column>
						
				        <p:column sortBy="#{tds.state}" headerText="#{bundle.state}" rendered="#{simulationBean.state eq null}" style="width:50px;text-align: center;">  
				        
				         
							<p:commandButton icon="fa fa-fw fa-file-o" style="opacity:0.65;" title="#{bundle.c}" rendered="#{tds.state eq 'c'}"/>
							
							<p:commandButton icon="fa fa-fw fa-power-off" style="color:#81c784;opacity:0.65;background-color: #81c784;" title="#{bundle.a}" rendered="#{tds.state eq 'a'}"/>
					        
					        <p:commandButton icon="fa fa-fw fa-power-off" style="color:#a1887f;opacity:0.65;background-color: #a1887f;" title="#{bundle.u}" rendered="#{tds.state eq 'u'}"/>
					        
					        <p:commandButton icon="fa fa-fw fa-exclamation-triangle" style="color:#dce775;opacity:0.65; background-color: #dce775;"  title="#{bundle.w}" rendered="#{tds.state eq 'w'}"/>
					         
  				            <p:commandButton icon="fa fa-fw fa-ban" style="color:#E57373;opacity:0.65; background-color: #E57373;" title="#{bundle.e}" rendered="#{tds.state eq 'e'}"/>
  				            						            
				              
				        </p:column>

				        <p:column sortBy="#{bundle.tds}" headerText="#{bundle.tdsCode}" style="width:100px;text-align: left;">  
				            <h:outputText value="#{tds.tds}" />  
				        </p:column>
				        <p:column sortBy="#{bundle.meterLine}" headerText="#{bundle.meterLine}" rendered="#{simulationBean.meterLine eq null}" style="width:80px;text-align: left;">  
				            <h:outputText value="#{tds.line}" />  
				        </p:column>
				        <p:column sortBy="#{bundle.meterModel}" headerText="#{bundle.meterModel}" rendered="#{simulationBean.meterModel eq null}" style="width:100px;text-align: left;">  
				            <h:outputText value="#{tds.model}" />  
				        </p:column>
						<p:columns value="#{simulationBean.columns}" var="column" columnIndexVar="colIndex" style="width:100px;text-align: left;" >
				            <f:facet name="header">
				                <h:outputText value="#{column.header}" />
				            </f:facet>
				            <h:outputText value="#{tds.values[colIndex]}" />
				        </p:columns>				        
					</p:dataTable>
				</p:outputPanel>	
			</div>
		</f:facet>
		<p:fieldset legend="#{bundle.filters}" toggleable="true" toggleSpeed="500">

			<h:outputText value="#{bundle.state}:" />  
			<p:selectOneMenu id="state" value="#{simulationBean.state}" style="height:30px;" title="#{bundle.selectMeterModelFilter}">  
            	<f:selectItem itemLabel="#{bundle.all}" itemValue="" />  
         			<f:selectItems var="state" itemLabel="#{state.getIntName()}" itemValue="#{state}" value="#{simulationBean.states}"  />
       		</p:selectOneMenu>							
		    <p:spacer width="10" />
   
   	  		<h:outputText value="#{bundle.line}:" />  
			<p:selectOneMenu id="line" value="#{simulationBean.meterLine}" style="height:30px;" converter="meterLineConverter" title="#{bundle.selectMeterLineFilter}">  
            	<f:selectItem itemLabel="#{bundle.all}" itemValue="" />  
       			<f:selectItems var="meter" itemLabel="#{meter.name}" itemValue="#{meter}" value="#{simulationBean.meterLines}"  />
				<p:ajax update="model gridFilter" listener="#{simulationBean.loadMeterModels}" process="@this" />		        		
			</p:selectOneMenu>							
	     	<p:spacer width="10" />
	     	
	   		<h:outputText value="#{bundle.model}:" />  
			<p:selectOneMenu id="model" value="#{simulationBean.meterModel}" style="height:30px;" converter="meterModelConverter" title="#{bundle.selectMeterModelFilter}">  
            	<f:selectItem itemLabel="#{bundle.all}" itemValue="" />  
          			<f:selectItems var="model" itemLabel="#{model.name}" itemValue="#{model}" value="#{simulationBean.meterModels}"  />
				<p:ajax update="gridFilter" listener="#{simulationBean.loadFilters}" process="@this" />		        		
       		</p:selectOneMenu>							
		    <p:spacer width="10" />

	   		<h:outputText value="#{bundle.tds}:" />  
			<p:inputText id="tds" value="#{simulationBean.tds}" />  
		    <p:spacer width="10" />

	     	<p:commandButton id="btSearch" icon="fa fa-search" actionListener="#{simulationBean.search}" ajax="true" update=":frmSimulation" title="#{bundle.search}"/>
	     	<p:commandButton id="btClear" icon="fa fa-eraser" actionListener="#{simulationBean.clear}" ajax="true" update=":frmSimulation" title="#{bundle.clear}"/>

			<br />
	     	<p:outputPanel id="gridFilter" style="background-color: #1C2B36;margin-top: 10px;">
		     	<p:dataGrid var="filter" value="#{simulationBean.filters}" columns="3" layout="grid" paginator="false" id="filters" rendered="#{simulationBean.filters ne null}">
		     		<p:outputPanel  style="float: right;" >
						<p:outputLabel for="filters" value="#{filter.header}:" />
				        <p:selectOneMenu id="sfilters" value="#{filter.value}" style="#{filter.value eq null || filter.value.isEmpty()  ? 'margin-top: 6px;height:30px;' : 'margin-top: 6px;height:30px;background-color:yellow'}">
			            	<f:selectItem itemLabel="#{bundle.all}" itemValue="" />  
	            			<f:selectItems var="model" itemLabel="#{model}" itemValue="#{model}" value="#{filter.options}"  />
	            			<p:ajax update="@this" />
				        </p:selectOneMenu>
			        </p:outputPanel>
			    </p:dataGrid>
		    </p:outputPanel>
	   </p:fieldset>				
	</p:panel>
</html>